modes_id = {
    "ARM": 0,
    "ANGLE": 1,
    "HORIZON": 2,
    "NAV ALTHOLD": 3,
    "HEADING HOLD": 5,
    "HEADFREE": 6,
    "HEADADJ": 7,
    "CAMSTAB": 8,
    "NAV RTH": 10,
    "NAV POSHOLD": 11,
    "MANUAL": 12,
    "BEEPER": 13,
    "LEDS OFF": 15,
    "LIGHTS": 16,
    "OSD OFF": 19,
    "TELEMETRY": 20,
    "AUTO TUNE": 21,
    "BLACKBOX": 26,
    "FAILSAFE": 27,
    "NAV WP": 28,
    "AIR MODE": 29,
    "HOME RESET": 30,
    "GCS NAV": 31,
    "FPV ANGLE MIX": 32,
    "SURFACE": 33,
    "FLAPERON": 34,
    "TURN ASSIST": 35,
    "NAV LAUNCH": 36,
    "SERVO AUTOTRIM": 37,
    "KILLSWITCH": 38,
    "CAMERA CONTROL 1": 39,
    "CAMERA CONTROL 2": 40,
    "CAMERA CONTROL 3": 41,
    "OSD ALT 1": 42,
    "OSD ALT 2": 43,
    "OSD ALT 3": 44,
    "NAV COURSE HOLD": 45,
    "MC BRAKING": 46,
    "USER1": 47,
    "USER2": 48,
    "LOITER CHANGE": 49,
    "MSP RC OVERRIDE": 50,
    "PREARM": 51,
    "TURTLE": 52,
    "NAV CRUISE": 53,
    "AUTO LEVEL": 54,
    "WP PLANNER": 55,
    "MISSION CHANGE": 59,
    "BEEPER MUTE": 60,
    "MULTI FUNCTION": 61,
    "MIXER PROFILE 2": 62,
    "MIXER TRANSITION": 63,
    "ANG HOLD": 64
}